apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  selector:
    matchLabels:
      app: employee
  replicas: 2
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee-1
          image: ameinberg/employee-service:latest
          ports:
            - containerPort: 8090
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: employee-svc
spec:
  selector:
    app: employee
  ports:
    - protocol: "TCP"
      port: 8090 # The port that the service is running on in the cluster
      targetPort: 8090 # The port exposed by the service
  type: NodePort # type of the service.